### ISSUE TITLE
Update to Nutch 2.1 with ParseFilter instead of HtmlParserFilter

### ISSUE THREAD

**Issue by ararog** [ATLANTBH/nutch-plugins#2]
Since nutch 2.0 the HtmlParserFilter was renamed to ParserFilter, the changes around ParseFilter are many, it would be nice to make filter-xpath Nutch 2.x compatible.

**Comment by emir-arnautovic** [comment]
We might soon need to start using these plugins again so might expect to make it compatible with new version of Nutch.

**Comment by ararog** [comment]
I did some changes to make it compatible with Nutch 2.1, but needs some testing.

**Comment by ararog** [comment]
Please let me know if I'm on the right way:

https://gist.github.com/3940997

**Comment by ararog** [comment]
I added a better encoding detection on parser filter, it fixed several issues that I had here. The encoding detection code was borrowed from parser-html HtmlParser class.

**Comment by ararog** [comment]
Removed the code borrowed from HtmlParser, now the plugin just pick from metadata the encoding detected by HtmlParser. The gist has been updated.

**Comment by developer1test** [comment]
Hi, 

Can you help me , i am using nutch 2.1. I have update both files from https://gist.github.com/3940997
After that plug-in build success fully  but when crawl data. It gives me error us under. 

root@sys47:/opt/nutch/runtime/local# bin/nutch crawl urls -depth 3 -topN 1
FetcherJob: threads: 10
FetcherJob: parsing: false
FetcherJob: resuming: false
FetcherJob : timelimit set for : -1
Using queue mode : byHost
Fetcher: threads: 10
QueueFeeder finished: total 1 records. Hit by time limit :0
fetching http://localhost.testcheck.com/
-finishing thread FetcherThread1, activeThreads=1
-finishing thread FetcherThread2, activeThreads=1
-finishing thread FetcherThread3, activeThreads=1
-finishing thread FetcherThread4, activeThreads=1
-finishing thread FetcherThread5, activeThreads=1
-finishing thread FetcherThread6, activeThreads=1
-finishing thread FetcherThread7, activeThreads=1
-finishing thread FetcherThread8, activeThreads=1
Fetcher: throughput threshold: -1
-finishing thread FetcherThread9, activeThreads=1
Fetcher: throughput threshold sequence: 5
-finishing thread FetcherThread0, activeThreads=0
0/0 spinwaiting/active, 1 pages, 0 errors, 0.2 0.2 pages/s, 1 1 kb/s, 0 URLs in 0 queues
-activeThreads=0
ParserJob: resuming:    false
ParserJob: forced reparse:  false
ParserJob: parsing all
Exception in thread "main" java.lang.NoClassDefFoundError: org/jaxen/JaxenException
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
    at java.lang.Class.getConstructor0(Class.java:2723)
    at java.lang.Class.newInstance0(Class.java:345)
    at java.lang.Class.newInstance(Class.java:327)
    at org.apache.nutch.plugin.Extension.getExtensionInstance(Extension.java:160)
    at org.apache.nutch.parse.ParseFilters.<init>(ParseFilters.java:63)
    at org.apache.nutch.parse.ParserJob.getFields(ParserJob.java:191)
    at org.apache.nutch.parse.ParserJob.run(ParserJob.java:245)
    at org.apache.nutch.crawl.Crawler.runTool(Crawler.java:68)
    at org.apache.nutch.crawl.Crawler.run(Crawler.java:171)
    at org.apache.nutch.crawl.Crawler.run(Crawler.java:250)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.nutch.crawl.Crawler.main(Crawler.java:257)
Caused by: java.lang.ClassNotFoundException: org.jaxen.JaxenException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 14 more

Please help me. anything missing or wrong . 

Thanks,
Dev

**Comment by emir-arnautovic** [comment]
It seems to me that you are missing jaxen jar on your classpath. That lib is used by XPathHtmlParserFilter.

**Comment by developer1test** [comment]
Hi, 

Thanks for response. but can you give more detail how to add that jaxen jar file? 

Thanks,
Dev

**Comment by developer1test** [comment]
Hi, 

I have put code following code in ivy.xml file of pulgin.
So jaxen.jar file inclue in runtime/local/plugin folder. 

dependency org="net.sourceforge.htmlcleaner" name="htmlcleaner" rev="2.2" conf="_->master"
        dependency org="jaxen" name="jaxen" rev="1.1.4" conf="_->master"

Thanks, 
Dev
